### PR TITLE
Issue 22 - Added documentation to chunk.h.

### LINKED ISSUE #22: As a part of issue #1, Document all the functions that are a part of the new chunk.h file

### PR DESCRIPTION
**Pull request by lukemoore495**

### CODE REVIEW

**Comment by lukemoore495** [comment]
I was a bit confused about the has_light and dirty_chunk functions, so if anybody has more detailed information then let me know.

**Review by fosterj14 — CHANGES_REQUESTED** [review]
Looks good. For the dirty chunk, I found this reddit post (https://www.reddit.com/r/gamedev/comments/yi7f0/comment/c5vst4z/?utm_source=share&utm_medium=web2x&context=3). I would guess it is a similar situation, so the function is setting it up so the game knows which chunks should be kept and which ones can be de-rendered. If a chunk is set to a dirty value of 1, then that means the player recently was in that chunk so it shouldn't be removed when a player moves to a new chunk until it becomes the oldest dirty chunk and a new dirty chunk needs to be added. For the light, that might be to keep track of the chunks that the player can see from their current chunk, so anything the light touches from the chunk the player is at, set it to dirty so it will remain rendered.

**Comment by lukemoore495** [comment]
> Looks good. For the dirty chunk, I found this reddit post (https://www.reddit.com/r/gamedev/comments/yi7f0/comment/c5vst4z/?utm_source=share&utm_medium=web2x&context=3). I would guess it is a similar situation, so the function is setting it up so the game knows which chunks should be kept and which ones can be de-rendered. If a chunk is set to a dirty value of 1, then that means the player recently was in that chunk so it shouldn't be removed when a player moves to a new chunk until it becomes the oldest dirty chunk and a new dirty chunk needs to be added. For the light, that might be to keep track of the chunks that the player can see from their current chunk, so anything the light touches from the chunk the player is at, set it to dirty so it will remain rendered.

This was very helpful information. Thank you. I tweaked the documentation.

**Review by fosterj14 — APPROVED** [review]
The new changes look good. This will help if we need to use this file to accomplish other stories

**Pull request merged**
